services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: 2242
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5 

    networks:
      - net_my


  redis-cache:
    restart: always
    image: redis:7.4.5
    ports:
     - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass 2242
    volumes:
      - redis_cache:/data

    networks:
      - net_my
        
      

  my_app: 
    image: webapp
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - net_my
      

    environment:
      DATABASE_URL: "postgres://postgres:2242@postgres/mydb"



networks: 
  net_my:

volumes:
  postgres_data:
    driver: local

  redis_cache:
    driver: local
